[package]
name = "temporary-dev"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1", features = ["add"] }
jsonrpc-http-server = "18.0"
maybe_static = "0.1.3"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
