/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

	public static class HelloNative {
		static {
			System.loadLibrary("sample");
		}

		public native void sayHello();
	}

    public static void main(String[] args) {
		new HelloNative().sayHello();
    }

}
